FROM eclipse-temurin:17-jdk as builder
WORKDIR /app
COPY . .
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=builder /app/target/*.jar api-gateway.jar
EXPOSE 8000
ENTRYPOINT ["java", "-jar", "api-gateway.jar"]