server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: keycloak-service
          uri: http://keycloak:8080
          predicates:
            - Path=/auth/**
          filters:
            - PreserveHostHeader
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/auth/realms/ecommerce

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    root: info