server:
  port: 8081

spring:
  application:
    name: product-service

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    preferIpAddress: true


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  show-actuator: true
  packages-to-scan: com.bytercoder.ecommerce.product.controller

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"